/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Disposition = "required" | "optional" | "disallowed";

export interface DnslintSchemaJson {
  $schema?: string;
  additionalProperties?: false;
  aws?: Source;
  domains?: Domain[];
  servers?: Server[];
}
export interface Source {
  enabled?: boolean;
  filter?: string;
}
export interface Domain {
  enabled?: boolean;
  name?: string;
  type?: string;
  records?: Record[];
  validations?: Validations;
}
export interface Record {
  enabled?: boolean;
  inheritable?: boolean;
  html?: boolean;
  addresses?: {
    enabled?: boolean;
    minimum?: number;
    [k: string]: unknown;
  };
  type?: string;
  timeout?: number;
  values?: Value[];
  webcalls?: WebcallValidation[];
}
export interface Value {
  disposition?: Disposition;
  name?: string;
  filter?:
    | string
    | {
        [k: string]: unknown;
      };
}
export interface WebcallValidation {
  callTimeMax?: number;
  enabled?: boolean;
  httpVersion?: string;
  port?: number;
  html?: boolean;
  headers?: Header[];
  statusCode?: number;
  timeout?: number;
  protocol?: string;
}
export interface Header {
  name?: string;
  value?: Value;
}
export interface Validations {
  crawl?: CrawlValidation[];
  enabled?: boolean;
  favicon?: FaviconlValidation[];
  robots?: RobotsValidation[];
  seo?: SeoValidation[];
  sitemap?: SitemapValidation[];
  social?: SocialValidation[];
  [k: string]: unknown;
}
export interface CrawlValidation {
  enabled?: boolean;
  [k: string]: unknown;
}
export interface FaviconlValidation {
  enabled?: boolean;
  [k: string]: unknown;
}
export interface RobotsValidation {
  enabled?: boolean;
  [k: string]: unknown;
}
export interface SeoValidation {
  enabled?: boolean;
  [k: string]: unknown;
}
export interface SitemapValidation {
  enabled?: boolean;
  files?: {
    0?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface SocialValidation {
  enabled?: boolean;
  [k: string]: unknown;
}
export interface Server {
  "*"?: boolean;
  filter?: string[];
  name?: string;
  records?: Record[];
  validations?: Validations;
}
